
TOKEN = ''

MEDIA_MATH = [
    'AgACAgIAAxkBAANzaITm8TdCGS6vG98RfH5jsFU2_SwAAjLzMRsj3SlIWXcP-ZMh8roBAAMCAAN5AAM2BA',
    'AgACAgIAAxkBAAN1aITm-4suGLBlqJJKXbFoDF59Kk0AAjPzMRsj3SlIbSOAA4feYqkBAAMCAAN5AAM2BA'
]

VOICE_MATH = [
    'AwACAgIAAxkBAANraITlxvsacnVVVmT0JeDGkmhNpbwAAmp1AAKJHSBIrU1nggABZokJNgQ'
]